# permissions for end users to edit ntps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ntp-editor-role
rules:
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - ntps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - ntps/status
  verbs:
  - get
